[phases.setup]
nixPkgs = ["python311", "libxcb", "libGL", "glib"]

[phases.install]
cmds = ["pip install -r requirements.txt", "python train_models.py"]

[start]
cmd = "streamlit run app.py --server.port 8080 --server.address 0.0.0.0"
